# Generated by Django 3.2.25 on 2025-06-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
