# Generated by Django 3.2.25 on 2025-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_on',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='2025studentproject@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
