# Generated by Django 3.2.25 on 2025-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contact_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
