# Generated by Django 3.2.25 on 2024-10-31 09:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_town_or_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(default='null', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
